#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: init.sh <CraftBukkit git repo>"
    echo
    echo "The required CB repo is generated by Spigot's BuildTools under ./Spigot/CraftBukkit"
    echo "The last commit should have a message like this:"
    echo
    echo "    CraftBukkit $ <build date>"

    exit 1
fi

CB_REPO=$1

pushd "$(dirname "$0")"

if [ ! -d .git ]; then
    echo "Git repository not found. Initializing..."
    git init
fi

git submodule update --init

git clone $CB_REPO base/CraftBukkit

popd
